workflows:
  build-android:
    name: Android APK Unique Theme Launcher
    instance_type: linux_vm
    environment:
      flutter: stable
    scripts:
      - name: Clean
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
